name: Download and then Upload Artifact

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * 0'

jobs:
  ncbi-taxonomy:
    env:
      URL: https://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz
      filename: taxdump.tar.gz
      localpath: ${{ github.workspace }}/taxdump.tar.gz
    runs-on: ubuntu-22.04
    steps:
      - name: install jq
        run: sudo apt-get install -y jq
      - name: Download folder from FTP
        run: |
          curl $URL > $localpath

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
            name: taxdump.tar.gz
            path: ${{ env.localpath }}
      - name: Get artifact URL
        run: |
          ARTIFACT_NAME=${{ env.filename }}
          RUN_ID="${{ github.run_id }}"
          REPO="${{ github.repository }}"
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          API_URL="https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts"
          ARTIFACT_ID=$(curl -s -H "Authorization: token $TOKEN" $API_URL | jq -r ".artifacts[] | select(.name==\"$ARTIFACT_NAME\") | .id")
          ARTIFACT_URL="https://github.com/$REPO/actions/artifacts/$ARTIFACT_ID"
          echo "Artifact URL: $ARTIFACT_URL"
          echo "artifact_url=$ARTIFACT_URL" >> $GITHUB_OUTPUT
  deploy:
    needs: ncbi-taxonomy
    steps:
      - name: Deploy website
        run: |
          echo "Deploying website using artifact URL: ${{ needs.ncbi-taxonomy.outputs.artifact_url }}"
          
          